function [pb,cb,pf,cf,Kf,K,sT,Tg,S,Qt,Kg,pg,cg,ri,rip,ro,rio,rg,ri2,u,HH,ui,HH2,big,rgs,bgs,rig,bpg,Sp,bpi,bsg,dSio,dSig,dSsg,dss,dVp,dVpi,dVg,dVs,TGp,xl,Df,Dg,Db]=loaddata;
% some default parameters listed below
pb = 2450;  %bulk density (kg m^3)
cb = 1000;  %bulk specific capacity, (j/kg 'C)
pf = 1000;  %fluid density (kg m^3)
cf = 4200; %fluid specific capacity, (j/kg 'C)
Kf = 0.6; %fluid conduct
K = 2.5;   %Thermal conductivity (W/ m K)
sT = 10;  %surface temperature ('C)
Tg = 0.02; %Temperature gradient ('C / 5 m)
S=1;% spacing
Qt=5; % injection temp
Kg = 2; %thermal conductivity of grout
pg = 1500; %density of grout
cg = 1200; %specific heat capacity of grout
Kp = 1.5; % thermal conductivity of pipe
ri=0.05; %radius of inner pipe
rip=0.12; %radius of outer pipe
ro=ri+0.01;
rio=rip+0.02;
rg=rio+0.04; % (m) radius to edge of grout
ri2=rip; %casing
D = ri*2; %inner diameter of well bore
u = 1; % extraction velocity 
Nu=500; %nusselt number
HH2= Nu.*(Kf./D);
D = rip*2; %inner diameter of well bore
ui = 0.2; %fluid injection rate
Nu=50;%nusselt number for injection pipe
HH= Nu.*(Kf./D); 
rig=(1./(ro./ri.*HH))+((ro.*log(ro/ri))./Kp)+(1./(ro./ri.*HH2));% Thermal resistance of piping
big = 1 / rig; %heat transfer coefficient for injection wellbore pipe-grout
rgs= (rg.*log(rg/rio))./Kg ;
bgs = 1/rgs;
Kp = 30;%conductivity of outer pipe
rig=(1./(rio./rip.*HH))+((rio.*log(rio/rip))./Kp);% Rfluid + Rpipematerial
bpg = 1 / rig; %heat transfer coefficient for injection wellbore pipe-grout
Sp=20; %vertical spacing for imaginary well
bpi =big;
bsg =bgs;  
dSio=2*pi*ro;
dSig = 2*pi*rio; %dSig is the contact surface area between injection well pipe and grout
dSsg = 2*pi*rg; %soil and grout 2?rh
dss=4*S;
dVp = (pi*ro^2);%area of volume of pipe
dVpi=pi*(rio^2-ro^2); 
dVg = (pi*(rg^2-rio^2)); %volume of grout
dVs = (S^2)-(pi*rg^2);
TGp=Tg;
xl=2820/Sp-1; %(Length of pipe)(-1)
Df=Kf./(cf.*pf); % fluid thermal diffusivity
Dg=Kg./(cg.*pg);% grout thermal diffusivity
Db=K./(pb.*cb);%rock thermal diffusivity
end